# Supported funding model platforms
#
# Funding for this project
# Support the core maintainer:
#
# - oldrepublicwizard (Benjamin Auquite): Core maintainer and project lead
#
# Individual maintainers will appear if they have GitHub Sponsors enabled

github: oldrepublicwizard
patreon: holowan-underlabs
open_collective: holowan-underlabs
