// Copyright 2021-2025 ModSync
// Licensed under the Business Source License 1.1 (BSL 1.1).
// See LICENSE.txt file in the project root for full license information.

using System;
using System.Globalization;
using System.IO;
using System.Text;

namespace ModSync.Tests.Fixtures
{
    /// <summary>
    /// Writes the instruction file that installs the synthetic mods into a mock install.
    /// <para>
    /// Two components, chosen so a silent no-op cannot pass: a loose-file extract that must add
    /// files to the override directory, and a TSLPatcher run that must append to dialog.tlk and add
    /// a row to a 2DA. The namespace archive is deliberately not installed - see the notes.
    /// </para>
    /// </summary>
    public static class MockBuildFile
    {
        /// <summary>Component name of the loose-file mod, as it appears in install logs.</summary>
        public const string LooseComponentName = "Mock Loose Files Mod";

        /// <summary>Component name of the TSLPatcher mod, as it appears in install logs.</summary>
        public const string PatcherComponentName = "Mock TSLPatcher Mod";

        /// <summary>
        /// Writes a TOML build file to <paramref name="path"/> targeting <paramref name="game"/>.
        /// </summary>
        public static string Write(string path, MockKotorGame game)
        {
            if (string.IsNullOrWhiteSpace(path))
            {
                throw new ArgumentException("A destination path is required.", nameof(path));
            }

            // K1 ships "Override", the Aspyr K2 layout ships "override". ModSync resolves the
            // destination case-sensitively on Linux, so the build file has to use the real casing.
            string overrideFolder = game == MockKotorGame.Kotor1 ? "Override" : "override";

            var sb = new StringBuilder();
            sb.Append("# Generated by ModSync.Tests MockBuildFile. Synthetic fixture, not a real mod build.\n");
            sb.Append("[metadata]\n");
            sb.Append("fileFormatVersion = \"2.0\"\n\n");

            sb.Append("[[thisMod]]\n");
            sb.Append("Guid = \"11111111-1111-1111-1111-111111111111\"\n");
            sb.Append("Name = \"").Append(LooseComponentName).Append("\"\n");
            sb.Append("IsSelected = true\n");
            sb.Append("Category = [\"Mock\"]\n");
            sb.Append("Language = [\"YES\"]\n\n");

            sb.Append("[[thisMod.Instructions]]\n");
            sb.Append("Guid = \"11111111-0000-0000-0000-000000000001\"\n");
            sb.Append("Action = \"Extract\"\n");
            sb.Append("Source = [\"<<modDirectory>>\\\\MockLooseFilesMod.zip\"]\n");
            sb.Append("Destination = \"<<kotorDirectory>>\\\\").Append(overrideFolder).Append("\"\n\n");

            sb.Append("[[thisMod]]\n");
            sb.Append("Guid = \"22222222-2222-2222-2222-222222222222\"\n");
            sb.Append("Name = \"").Append(PatcherComponentName).Append("\"\n");
            sb.Append("IsSelected = true\n");
            sb.Append("Category = [\"Mock\"]\n");
            sb.Append("Language = [\"YES\"]\n\n");

            sb.Append("[[thisMod.Instructions]]\n");
            sb.Append("Guid = \"22222222-0000-0000-0000-000000000001\"\n");
            sb.Append("Action = \"Extract\"\n");
            sb.Append("Source = [\"<<modDirectory>>\\\\MockTslPatcherMod.zip\"]\n");
            sb.Append("Destination = \"<<modDirectory>>\"\n\n");

            // The installer name is read from the archive, never assumed.
            sb.Append("[[thisMod.Instructions]]\n");
            sb.Append("Guid = \"22222222-0000-0000-0000-000000000002\"\n");
            sb.Append("Action = \"Patcher\"\n");
            sb.Append("Source = [\"<<modDirectory>>\\\\MockTslPatcherMod\\\\")
                .Append(MockModArchives.TslPatcherInstallerName)
                .Append("\"]\n");
            sb.Append("Destination = \"<<gameDirectory>>\"\n");

            string directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
            return path;
        }

        /// <summary>
        /// Command-line front end, reached through <c>ModSync.Tests</c>'s <c>make-mock-build</c> verb.
        /// </summary>
        public static int RunCli(string[] args)
        {
            string outputPath = null;
            MockKotorGame? game = null;

            for (int i = 0; i < args.Length; i++)
            {
                switch (args[i])
                {
                    case "--out":
                    case "-o":
                        outputPath = i + 1 < args.Length ? args[++i] : null;
                        break;
                    case "--game":
                    case "-g":
                        string value = i + 1 < args.Length ? args[++i] : null;
                        if (string.Equals(value, "k1", StringComparison.OrdinalIgnoreCase) || string.Equals(value, "kotor1", StringComparison.OrdinalIgnoreCase))
                        {
                            game = MockKotorGame.Kotor1;
                        }
                        else if (string.Equals(value, "k2", StringComparison.OrdinalIgnoreCase) || string.Equals(value, "kotor2", StringComparison.OrdinalIgnoreCase))
                        {
                            game = MockKotorGame.Kotor2;
                        }
                        else
                        {
                            Console.Error.WriteLine("make-mock-build: --game must be k1 or k2.");
                            return 2;
                        }

                        break;
                    case "-h":
                    case "--help":
                        Console.WriteLine("Usage: make-mock-build --game <k1|k2> --out <file.toml>");
                        return 0;
                    default:
                        Console.Error.WriteLine("make-mock-build: unknown argument '" + args[i] + "'.");
                        return 2;
                }
            }

            if (string.IsNullOrWhiteSpace(outputPath) || game is null)
            {
                Console.Error.WriteLine("make-mock-build: --out and --game are both required.");
                return 2;
            }

            string written = Write(outputPath, game.Value);
            Console.WriteLine("buildFile=" + Path.GetFullPath(written));
            Console.WriteLine("game=" + game.Value.ToString());
            Console.WriteLine("bytes=" + new FileInfo(written).Length.ToString(CultureInfo.InvariantCulture));
            return 0;
        }
    }
}
